# Generated by Django 4.2.7 on 2023-12-28 11:30

import cinystoreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinystoreapp', '0002_alter_userinfo_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profilephoto',
            field=models.ImageField(default='Users/blank_profile.webp', null=True, upload_to=cinystoreapp.models.rename),
        ),
    ]
