# Generated by Django 4.2.7 on 2023-12-18 05:16

import cinystoreapp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinystoreapp', '0003_alter_userinfo_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('overview', models.TextField(max_length=1000)),
                ('release_date', models.DateField(max_length=100, null=True)),
                ('poster_path', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('genre', models.CharField(default=False, max_length=100, null=True)),
                ('language', models.CharField(default=False, max_length=50, null=True)),
                ('video', models.URLField(default=False, null=True)),
                ('producer', models.CharField(default=False, max_length=100, null=True)),
                ('director', models.CharField(default=False, max_length=100, null=True)),
                ('music_director', models.CharField(default=False, max_length=100, null=True)),
                ('crew', models.CharField(default=False, max_length=100, null=True)),
                ('cast', models.CharField(default=False, max_length=2000, null=True)),
                ('timestamp_field', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_type', models.CharField(default='recent_movies', max_length=50)),
                ('like_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('follow_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('share_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('comment_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('source', models.CharField(blank=True, default='TMDB', max_length=100, null=True)),
                ('logo', models.CharField(blank=True, default='TMDB/TMDB_logo.png', max_length=100, null=True)),
                ('slug', models.SlugField(default=False)),
            ],
            options={
                'db_table': 'recent_movies',
                'ordering': ['-timestamp_field'],
            },
        ),
        migrations.CreateModel(
            name='TopRatedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('overview', models.TextField(max_length=1000)),
                ('release_date', models.DateField(max_length=100, null=True)),
                ('poster_path', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('genre', models.CharField(default=False, max_length=100, null=True)),
                ('language', models.CharField(default=False, max_length=50, null=True)),
                ('video', models.URLField(default=False, null=True)),
                ('producer', models.CharField(default=False, max_length=100, null=True)),
                ('director', models.CharField(default=False, max_length=100, null=True)),
                ('music_director', models.CharField(default=False, max_length=100, null=True)),
                ('crew', models.CharField(default=False, max_length=100, null=True)),
                ('cast', models.CharField(default=False, max_length=2000, null=True)),
                ('timestamp_field', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_type', models.CharField(default='top_rated_movies', max_length=50)),
                ('like_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('follow_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('share_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('comment_count', models.BigIntegerField(blank=True, default='0', null=True)),
                ('source', models.CharField(blank=True, default='TMDB', max_length=100, null=True)),
                ('logo', models.CharField(blank=True, default='TMDB/TMDB_logo.png', max_length=100, null=True)),
                ('slug', models.SlugField(default=False)),
            ],
            options={
                'db_table': 'top_rated_movies',
                'ordering': ['-timestamp_field'],
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profilephoto',
            field=models.ImageField(default='Users/blank_profile.webp', null=True, upload_to=cinystoreapp.models.rename),
        ),
    ]
