# Generated by Django 4.2.7 on 2023-12-18 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinystoreapp', '0002_alter_userinfo_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRegister',
            fields=[
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('production_house', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('company_brief', models.CharField(max_length=2000)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'AgencyRegister',
            },
        ),
        migrations.CreateModel(
            name='CorporateRegister',
            fields=[
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('production_house', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('company_brief', models.CharField(max_length=2000)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CorporateRegister',
            },
        ),
        migrations.CreateModel(
            name='IndividualRegister',
            fields=[
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('production_house', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('company_brief', models.CharField(max_length=2000)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'IndividualRegister',
            },
        ),
        migrations.CreateModel(
            name='OttRegister',
            fields=[
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('production_house', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('company_brief', models.CharField(max_length=2000)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'OttRegister',
            },
        ),
    ]
